DROP DATABASE IF EXISTS hollywood;
CREATE DATABASE hollywood;
USE hollywood;

CREATE TABLE hollywood.people (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	born DATE );
	
CREATE TABLE hollywood.movies (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	released DATE NOT NULL,
	tagline VARCHAR(1024) );
	
CREATE TABLE hollywood.roles (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	role VARCHAR(255) NOT NULL,
	movie INTEGER NOT NULL, 
	actor INTEGER NOT NULL,
	FOREIGN KEY (movie) REFERENCES movies(id), 
	FOREIGN KEY (actor) REFERENCES people(id) );
	
CREATE TABLE hollywood.reviews (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	movie INTEGER NOT NULL,
	author INTEGER NOT NULL,
	summary VARCHAR(1024) NOT NULL,
	rating INTEGER NOT NULL,
	FOREIGN KEY (movie) REFERENCES movies(id), 
	FOREIGN KEY (author) REFERENCES people(id) );
	
CREATE TABLE hollywood.wrote (
	movie INTEGER NOT NULL,
	author INTEGER NOT NULL,
	FOREIGN KEY (movie) REFERENCES movies(id), 
	FOREIGN KEY (author) REFERENCES people(id) );

CREATE TABLE hollywood.directed (
	movie INTEGER NOT NULL,
	director INTEGER NOT NULL,
	FOREIGN KEY (movie) REFERENCES movies(id), 
	FOREIGN KEY (director) REFERENCES people(id) );
	
CREATE TABLE hollywood.produced (
	movie INTEGER NOT NULL,
	producer INTEGER NOT NULL,
	FOREIGN KEY (movie) REFERENCES movies(id), 
	FOREIGN KEY (producer) REFERENCES people(id) );


INSERT INTO people (name, born) VALUES ('Keanu Reeves', 19640101);
INSERT INTO people (name, born) VALUES ('Carrie-Anne Moss', 19670101);
INSERT INTO people (name, born) VALUES ('Laurence Fishburne', 19610101);
INSERT INTO people (name, born) VALUES ('Hugo Weaving', 19600101);
INSERT INTO people (name, born) VALUES ('Andy Wachowski', 19670101);
INSERT INTO people (name, born) VALUES ('Lana Wachowski', 19650101);
INSERT INTO people (name, born) VALUES ('Joel Silver', 19520101);
INSERT INTO people (name, born) VALUES ('Emil Eifrem', 19780101);
INSERT INTO people (name, born) VALUES ('Charlize Theron', 19750101);
INSERT INTO people (name, born) VALUES ('Al Pacino', 19400101);
INSERT INTO people (name, born) VALUES ('Taylor Hackford', 19440101);
INSERT INTO people (name, born) VALUES ('Tom Cruise', 19620101);
INSERT INTO people (name, born) VALUES ('Jack Nicholson', 19370101);
INSERT INTO people (name, born) VALUES ('Demi Moore', 19620101);
INSERT INTO people (name, born) VALUES ('Kevin Bacon', 19580101);
INSERT INTO people (name, born) VALUES ('Kiefer Sutherland', 19660101);
INSERT INTO people (name, born) VALUES ('Noah Wyle', 19710101);
INSERT INTO people (name, born) VALUES ('Cuba Gooding Jr.', 19680101);
INSERT INTO people (name, born) VALUES ('Kevin Pollak', 19570101);
INSERT INTO people (name, born) VALUES ('J.T. Walsh', 19430101);
INSERT INTO people (name, born) VALUES ('James Marshall', 19670101);
INSERT INTO people (name, born) VALUES ('Christopher Guest', 19480101);
INSERT INTO people (name, born) VALUES ('Rob Reiner', 19470101);
INSERT INTO people (name, born) VALUES ('Aaron Sorkin', 19610101);
INSERT INTO people (name, born) VALUES ('Kelly McGillis', 19570101);
INSERT INTO people (name, born) VALUES ('Val Kilmer', 19590101);
INSERT INTO people (name, born) VALUES ('Anthony Edwards', 19620101);
INSERT INTO people (name, born) VALUES ('Tom Skerritt', 19330101);
INSERT INTO people (name, born) VALUES ('Meg Ryan', 19610101);
INSERT INTO people (name, born) VALUES ('Tony Scott', 19440101);
INSERT INTO people (name, born) VALUES ('Jim Cash', 19410101);
INSERT INTO people (name, born) VALUES ('Renee Zellweger', 19690101);
INSERT INTO people (name, born) VALUES ('Kelly Preston', 19620101);
INSERT INTO people (name, born) VALUES ('Jerry O\'Connell', 19740101);
INSERT INTO people (name, born) VALUES ('Jay Mohr', 19700101);
INSERT INTO people (name, born) VALUES ('Bonnie Hunt', 19610101);
INSERT INTO people (name, born) VALUES ('Regina King', 19710101);
INSERT INTO people (name, born) VALUES ('Jonathan Lipnicki', 19900101);
INSERT INTO people (name, born) VALUES ('Cameron Crowe', 19570101);
INSERT INTO people (name, born) VALUES ('River Phoenix', 19700101);
INSERT INTO people (name, born) VALUES ('Corey Feldman', 19710101);
INSERT INTO people (name, born) VALUES ('Wil Wheaton', 19720101);
INSERT INTO people (name, born) VALUES ('John Cusack', 19660101);
INSERT INTO people (name, born) VALUES ('Marshall Bell', 19420101);
INSERT INTO people (name, born) VALUES ('Helen Hunt', 19630101);
INSERT INTO people (name, born) VALUES ('Greg Kinnear', 19630101);
INSERT INTO people (name, born) VALUES ('James L. Brooks', 19400101);
INSERT INTO people (name, born) VALUES ('Annabella Sciorra', 19600101);
INSERT INTO people (name, born) VALUES ('Max von Sydow', 19290101);
INSERT INTO people (name, born) VALUES ('Werner Herzog', 19420101);
INSERT INTO people (name, born) VALUES ('Robin Williams', 19510101);
INSERT INTO people (name, born) VALUES ('Vincent Ward', 19560101);
INSERT INTO people (name, born) VALUES ('Ethan Hawke', 19700101);
INSERT INTO people (name, born) VALUES ('Rick Yune', 19710101);
INSERT INTO people (name, born) VALUES ('James Cromwell', 19400101);
INSERT INTO people (name, born) VALUES ('Scott Hicks', 19530101);
INSERT INTO people (name, born) VALUES ('Parker Posey', 19680101);
INSERT INTO people (name, born) VALUES ('Dave Chappelle', 19730101);
INSERT INTO people (name, born) VALUES ('Steve Zahn', 19670101);
INSERT INTO people (name, born) VALUES ('Tom Hanks', 19560101);
INSERT INTO people (name, born) VALUES ('Nora Ephron', 19410101);
INSERT INTO people (name, born) VALUES ('Rita Wilson', 19560101);
INSERT INTO people (name, born) VALUES ('Bill Pullman', 19530101);
INSERT INTO people (name, born) VALUES ('Victor Garber', 19490101);
INSERT INTO people (name, born) VALUES ('Rosie O\'Donnell', 19620101);
INSERT INTO people (name, born) VALUES ('John Patrick Stanley', 19500101);
INSERT INTO people (name, born) VALUES ('Nathan Lane', 19560101);
INSERT INTO people (name, born) VALUES ('Billy Crystal', 19480101);
INSERT INTO people (name, born) VALUES ('Carrie Fisher', 19560101);
INSERT INTO people (name, born) VALUES ('Bruno Kirby', 19490101);
INSERT INTO people (name, born) VALUES ('Liv Tyler', 19770101);
INSERT INTO people (name, born) VALUES ('Brooke Langton', 19700101);
INSERT INTO people (name, born) VALUES ('Gene Hackman', 19300101);
INSERT INTO people (name, born) VALUES ('Orlando Jones', 19680101);
INSERT INTO people (name, born) VALUES ('Howard Deutch', 19500101);
INSERT INTO people (name, born) VALUES ('Christian Bale', 19740101);
INSERT INTO people (name, born) VALUES ('Zach Grenier', 19540101);
INSERT INTO people (name, born) VALUES ('Mike Nichols', 19310101);
INSERT INTO people (name, born) VALUES ('Richard Harris', 19300101);
INSERT INTO people (name, born) VALUES ('Clint Eastwood', 19300101);
INSERT INTO people (name, born) VALUES ('Takeshi Kitano', 19470101);
INSERT INTO people (name, born) VALUES ('Dina Meyer', 19680101);
INSERT INTO people (name, born) VALUES ('Ice-T', 19580101);
INSERT INTO people (name, born) VALUES ('Robert Longo', 19530101);
INSERT INTO people (name, born) VALUES ('Halle Berry', 19660101);
INSERT INTO people (name, born) VALUES ('Jim Broadbent', 19490101);
INSERT INTO people (name, born) VALUES ('Tom Tykwer', 19650101);
INSERT INTO people (name, born) VALUES ('David Mitchell', 19690101);
INSERT INTO people (name, born) VALUES ('Stefan Arndt', 19610101);
INSERT INTO people (name, born) VALUES ('Ian McKellen', 19390101);
INSERT INTO people (name, born) VALUES ('Audrey Tautou', 19760101);
INSERT INTO people (name, born) VALUES ('Paul Bettany', 19710101);
INSERT INTO people (name, born) VALUES ('Ron Howard', 19540101);
INSERT INTO people (name, born) VALUES ('Natalie Portman', 19810101);
INSERT INTO people (name, born) VALUES ('Stephen Rea', 19460101);
INSERT INTO people (name, born) VALUES ('John Hurt', 19400101);
INSERT INTO people (name, born) VALUES ('Ben Miles', 19670101);
INSERT INTO people (name, born) VALUES ('Emile Hirsch', 19850101);
INSERT INTO people (name, born) VALUES ('John Goodman', 19600101);
INSERT INTO people (name, born) VALUES ('Susan Sarandon', 19460101);
INSERT INTO people (name, born) VALUES ('Matthew Fox', 19660101);
INSERT INTO people (name, born) VALUES ('Christina Ricci', 19800101);
INSERT INTO people (name, born) VALUES ('Rain', 19820101);
INSERT INTO people (name) VALUES ('Naomie Harris');
INSERT INTO people (name, born) VALUES ('Michael Clarke Duncan', 19570101);
INSERT INTO people (name, born) VALUES ('David Morse', 19530101);
INSERT INTO people (name, born) VALUES ('Sam Rockwell', 19680101);
INSERT INTO people (name, born) VALUES ('Gary Sinise', 19550101);
INSERT INTO people (name, born) VALUES ('Patricia Clarkson', 19590101);
INSERT INTO people (name, born) VALUES ('Frank Darabont', 19590101);
INSERT INTO people (name, born) VALUES ('Frank Langella', 19380101);
INSERT INTO people (name, born) VALUES ('Michael Sheen', 19690101);
INSERT INTO people (name, born) VALUES ('Oliver Platt', 19600101);
INSERT INTO people (name, born) VALUES ('Danny DeVito', 19440101);
INSERT INTO people (name, born) VALUES ('John C. Reilly', 19650101);
INSERT INTO people (name, born) VALUES ('Ed Harris', 19500101);
INSERT INTO people (name, born) VALUES ('Bill Paxton', 19550101);
INSERT INTO people (name, born) VALUES ('Philip Seymour Hoffman', 19670101);
INSERT INTO people (name, born) VALUES ('Jan de Bont', 19430101);
INSERT INTO people (name, born) VALUES ('Robert Zemeckis', 19510101);
INSERT INTO people (name, born) VALUES ('Milos Forman', 19320101);
INSERT INTO people (name, born) VALUES ('Diane Keaton', 19460101);
INSERT INTO people (name, born) VALUES ('Nancy Meyers', 19490101);
INSERT INTO people (name, born) VALUES ('Chris Columbus', 19580101);
INSERT INTO people (name, born) VALUES ('Julia Roberts', 19670101);
INSERT INTO people (name, born) VALUES ('Madonna', 19540101);
INSERT INTO people (name, born) VALUES ('Geena Davis', 19560101);
INSERT INTO people (name, born) VALUES ('Lori Petty', 19630101);
INSERT INTO people (name, born) VALUES ('Penny Marshall', 19430101);
INSERT INTO people (name) VALUES ('Paul Blythe');
INSERT INTO people (name) VALUES ('Angela Scope');
INSERT INTO people (name) VALUES ('Jessica Thompson');
INSERT INTO people (name) VALUES ('James Thompson');
INSERT INTO movies (title, tagline, released) VALUES ('The Matrix', 'Welcome to the Real World', 19990101);
INSERT INTO movies (title, tagline, released) VALUES ('The Matrix Reloaded', 'Free your mind', 20030101);
INSERT INTO movies (title, tagline, released) VALUES ('The Matrix Revolutions', 'Everything that has a beginning has an end', 20030101);
INSERT INTO movies (title, tagline, released) VALUES ('The Devil\'s Advocate', 'Evil has its winning ways', 19970101);
INSERT INTO movies (title, tagline, released) VALUES ('A Few Good Men', 'In the heart of the nation\'s capital, in a courthouse of the U.S. government, one man will stop at nothing to keep his honor, and one will stop at nothing to find the truth.', 19920101);
INSERT INTO movies (title, tagline, released) VALUES ('Top Gun', 'I feel the need, the need for speed.', 19860101);
INSERT INTO movies (title, tagline, released) VALUES ('Jerry Maguire', 'The rest of his life begins now.', 20000101);
INSERT INTO movies (title, tagline, released) VALUES ('Stand By Me', 'For some, it\'s the last real taste of innocence, and the first real taste of life. But for everyone, it\'s the time that memories are made of.', 19950101);
INSERT INTO movies (title, tagline, released) VALUES ('As Good as It Gets', 'A comedy from the heart that goes for the throat.', 19970101);
INSERT INTO movies (title, tagline, released) VALUES ('What Dreams May Come', 'After life there is more. The end is just the beginning.', 19980101);
INSERT INTO movies (title, tagline, released) VALUES ('Snow Falling on Cedars', 'First loves last. Forever.', 19990101);
INSERT INTO movies (title, tagline, released) VALUES ('You\'ve Got Mail', 'At odds in life... in love on-line.', 19980101);
INSERT INTO movies (title, tagline, released) VALUES ('Sleepless in Seattle', 'What if someone you never met, someone you never saw, someone you never knew was the only someone for you?', 19930101);
INSERT INTO movies (title, tagline, released) VALUES ('Joe Versus the Volcano', 'A story of love, lava and burning desire.', 19900101);
INSERT INTO movies (title, tagline, released) VALUES ('When Harry Met Sally', 'At odds in life... in love on-line.', 19980101);
INSERT INTO movies (title, tagline, released) VALUES ('That Thing You Do', 'In every life there comes a time when that thing you dream becomes that thing you do', 19960101);
INSERT INTO movies (title, tagline, released) VALUES ('The Replacements', 'Pain heals, Chicks dig scars... Glory lasts forever', 20000101);
INSERT INTO movies (title, tagline, released) VALUES ('RescueDawn', 'Based on the extraordinary true story of one man\'s fight for freedom', 20060101);
INSERT INTO movies (title, tagline, released) VALUES ('The Birdcage', 'Come as you are', 19960101);
INSERT INTO movies (title, tagline, released) VALUES ('Unforgiven', 'It\'s a hell of a thing, killing a man', 19920101);
INSERT INTO movies (title, tagline, released) VALUES ('Johnny Mnemonic', 'The hottest data on earth. In the coolest head in town', 19950101);
INSERT INTO movies (title, tagline, released) VALUES ('Cloud Atlas', 'Everything is connected', 20120101);
INSERT INTO movies (title, tagline, released) VALUES ('The Da Vinci Code', 'Break The Codes', 20060101);
INSERT INTO movies (title, tagline, released) VALUES ('V for Vendetta', 'Freedom! Forever!', 20060101);
INSERT INTO movies (title, tagline, released) VALUES ('Speed Racer', 'Speed has no limits', 20080101);
INSERT INTO movies (title, tagline, released) VALUES ('Ninja Assassin', 'Prepare to enter a secret world of assassins', 20090101);
INSERT INTO movies (title, tagline, released) VALUES ('The Green Mile', 'Walk a mile you\'ll never forget.', 19990101);
INSERT INTO movies (title, tagline, released) VALUES ('Frost/Nixon', '400 million people were waiting for the truth.', 20080101);
INSERT INTO movies (title, tagline, released) VALUES ('Hoffa', 'He didn\'t want law. He wanted justice.', 19920101);
INSERT INTO movies (title, tagline, released) VALUES ('Apollo 13', 'Houston, we have a problem.', 19950101);
INSERT INTO movies (title, tagline, released) VALUES ('Twister', 'Don\'t Breathe. Don\'t Look Back.', 19960101);
INSERT INTO movies (title, tagline, released) VALUES ('Cast Away', 'At the edge of the world, his journey begins.', 20000101);
INSERT INTO movies (title, tagline, released) VALUES ('One Flew Over the Cuckoo\'s Nest', 'If he\'s crazy, what does that make you?', 19750101);
INSERT INTO movies (title, released) VALUES ('Something\'s Gotta Give', 19750101);
INSERT INTO movies (title, tagline, released) VALUES ('Bicentennial Man', 'One robot\'s 200 year journey to become an ordinary man.', 19990101);
INSERT INTO movies (title, tagline, released) VALUES ('Charlie Wilson\'s War', 'A stiff drink. A little mascara. A lot of nerve. Who said they couldn\'t bring down the Soviet empire.', 20070101);
INSERT INTO movies (title, tagline, released) VALUES ('The Polar Express', 'This Holiday Season… Believe', 20040101);
INSERT INTO movies (title, tagline, released) VALUES ('A League of Their Own', 'Once in a lifetime you get a chance to do something different.', 19920101);
INSERT INTO roles (role, actor, movie) VALUES ( 'Neo', (SELECT id FROM people WHERE people.name = 'Keanu Reeves'), (SELECT id FROM movies WHERE movies.title = 'The Matrix') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Neo', (SELECT id FROM people WHERE people.name = 'Keanu Reeves'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Reloaded') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Neo', (SELECT id FROM people WHERE people.name = 'Keanu Reeves'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Revolutions') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Kevin Lomax', (SELECT id FROM people WHERE people.name = 'Keanu Reeves'), (SELECT id FROM movies WHERE movies.title = 'The Devil\'s Advocate') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Shane Falco', (SELECT id FROM people WHERE people.name = 'Keanu Reeves'), (SELECT id FROM movies WHERE movies.title = 'The Replacements') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Johnny Mnemonic', (SELECT id FROM people WHERE people.name = 'Keanu Reeves'), (SELECT id FROM movies WHERE movies.title = 'Johnny Mnemonic') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Julian Mercer', (SELECT id FROM people WHERE people.name = 'Keanu Reeves'), (SELECT id FROM movies WHERE movies.title = 'Something\'s Gotta Give') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Trinity', (SELECT id FROM people WHERE people.name = 'Carrie-Anne Moss'), (SELECT id FROM movies WHERE movies.title = 'The Matrix') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Trinity', (SELECT id FROM people WHERE people.name = 'Carrie-Anne Moss'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Reloaded') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Trinity', (SELECT id FROM people WHERE people.name = 'Carrie-Anne Moss'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Revolutions') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Morpheus', (SELECT id FROM people WHERE people.name = 'Laurence Fishburne'), (SELECT id FROM movies WHERE movies.title = 'The Matrix') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Morpheus', (SELECT id FROM people WHERE people.name = 'Laurence Fishburne'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Reloaded') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Morpheus', (SELECT id FROM people WHERE people.name = 'Laurence Fishburne'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Revolutions') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Agent Smith', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'The Matrix') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Agent Smith', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Reloaded') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Agent Smith', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Revolutions') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Bill Smoke', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Haskell Moore', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Tadeusz Kesselring', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Nurse Noakes', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Boardman Mephi', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Old Georgie', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'V', (SELECT id FROM people WHERE people.name = 'Hugo Weaving'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Emil', (SELECT id FROM people WHERE people.name = 'Emil Eifrem'), (SELECT id FROM movies WHERE movies.title = 'The Matrix') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Mary Ann Lomax', (SELECT id FROM people WHERE people.name = 'Charlize Theron'), (SELECT id FROM movies WHERE movies.title = 'The Devil\'s Advocate') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Tina', (SELECT id FROM people WHERE people.name = 'Charlize Theron'), (SELECT id FROM movies WHERE movies.title = 'That Thing You Do') );
INSERT INTO roles (role, actor, movie) VALUES ( 'John Milton', (SELECT id FROM people WHERE people.name = 'Al Pacino'), (SELECT id FROM movies WHERE movies.title = 'The Devil\'s Advocate') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Lt. Daniel Kaffee', (SELECT id FROM people WHERE people.name = 'Tom Cruise'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Maverick', (SELECT id FROM people WHERE people.name = 'Tom Cruise'), (SELECT id FROM movies WHERE movies.title = 'Top Gun') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jerry Maguire', (SELECT id FROM people WHERE people.name = 'Tom Cruise'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Col. Nathan R. Jessup', (SELECT id FROM people WHERE people.name = 'Jack Nicholson'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Melvin Udall', (SELECT id FROM people WHERE people.name = 'Jack Nicholson'), (SELECT id FROM movies WHERE movies.title = 'As Good as It Gets') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Hoffa', (SELECT id FROM people WHERE people.name = 'Jack Nicholson'), (SELECT id FROM movies WHERE movies.title = 'Hoffa') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Randle McMurphy', (SELECT id FROM people WHERE people.name = 'Jack Nicholson'), (SELECT id FROM movies WHERE movies.title = 'One Flew Over the Cuckoo\'s Nest') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Harry Sanborn', (SELECT id FROM people WHERE people.name = 'Jack Nicholson'), (SELECT id FROM movies WHERE movies.title = 'Something\'s Gotta Give') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Lt. Cdr. JoAnne Galloway', (SELECT id FROM people WHERE people.name = 'Demi Moore'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Capt. Jack Ross', (SELECT id FROM people WHERE people.name = 'Kevin Bacon'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jack Brennan', (SELECT id FROM people WHERE people.name = 'Kevin Bacon'), (SELECT id FROM movies WHERE movies.title = 'Frost/Nixon') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jack Swigert', (SELECT id FROM people WHERE people.name = 'Kevin Bacon'), (SELECT id FROM movies WHERE movies.title = 'Apollo 13') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Lt. Jonathan Kendrick', (SELECT id FROM people WHERE people.name = 'Kiefer Sutherland'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Ace Merrill', (SELECT id FROM people WHERE people.name = 'Kiefer Sutherland'), (SELECT id FROM movies WHERE movies.title = 'Stand By Me') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Cpl. Jeffrey Barnes', (SELECT id FROM people WHERE people.name = 'Noah Wyle'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Cpl. Carl Hammaker', (SELECT id FROM people WHERE people.name = 'Cuba Gooding Jr.'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Rod Tidwell', (SELECT id FROM people WHERE people.name = 'Cuba Gooding Jr.'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Frank Sachs', (SELECT id FROM people WHERE people.name = 'Cuba Gooding Jr.'), (SELECT id FROM movies WHERE movies.title = 'As Good as It Gets') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Albert Lewis', (SELECT id FROM people WHERE people.name = 'Cuba Gooding Jr.'), (SELECT id FROM movies WHERE movies.title = 'What Dreams May Come') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Lt. Sam Weinberg', (SELECT id FROM people WHERE people.name = 'Kevin Pollak'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Lt. Col. Matthew Andrew Markinson', (SELECT id FROM people WHERE people.name = 'J.T. Walsh'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Frank Fitzsimmons', (SELECT id FROM people WHERE people.name = 'J.T. Walsh'), (SELECT id FROM movies WHERE movies.title = 'Hoffa') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Pfc. Louden Downey', (SELECT id FROM people WHERE people.name = 'James Marshall'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dr. Stone', (SELECT id FROM people WHERE people.name = 'Christopher Guest'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Man in Bar', (SELECT id FROM people WHERE people.name = 'Aaron Sorkin'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Charlie', (SELECT id FROM people WHERE people.name = 'Kelly McGillis'), (SELECT id FROM movies WHERE movies.title = 'Top Gun') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Iceman', (SELECT id FROM people WHERE people.name = 'Val Kilmer'), (SELECT id FROM movies WHERE movies.title = 'Top Gun') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Goose', (SELECT id FROM people WHERE people.name = 'Anthony Edwards'), (SELECT id FROM movies WHERE movies.title = 'Top Gun') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Viper', (SELECT id FROM people WHERE people.name = 'Tom Skerritt'), (SELECT id FROM movies WHERE movies.title = 'Top Gun') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Carole', (SELECT id FROM people WHERE people.name = 'Meg Ryan'), (SELECT id FROM movies WHERE movies.title = 'Top Gun') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Kathleen Kelly', (SELECT id FROM people WHERE people.name = 'Meg Ryan'), (SELECT id FROM movies WHERE movies.title = 'You\'ve Got Mail') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Annie Reed', (SELECT id FROM people WHERE people.name = 'Meg Ryan'), (SELECT id FROM movies WHERE movies.title = 'Sleepless in Seattle') );
INSERT INTO roles (role, actor, movie) VALUES ( 'DeDe', (SELECT id FROM people WHERE people.name = 'Meg Ryan'), (SELECT id FROM movies WHERE movies.title = 'Joe Versus the Volcano') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Angelica Graynamore', (SELECT id FROM people WHERE people.name = 'Meg Ryan'), (SELECT id FROM movies WHERE movies.title = 'Joe Versus the Volcano') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Patricia Graynamore', (SELECT id FROM people WHERE people.name = 'Meg Ryan'), (SELECT id FROM movies WHERE movies.title = 'Joe Versus the Volcano') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Sally Albright', (SELECT id FROM people WHERE people.name = 'Meg Ryan'), (SELECT id FROM movies WHERE movies.title = 'When Harry Met Sally') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dorothy Boyd', (SELECT id FROM people WHERE people.name = 'Renee Zellweger'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Avery Bishop', (SELECT id FROM people WHERE people.name = 'Kelly Preston'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Frank Cushman', (SELECT id FROM people WHERE people.name = 'Jerry O\'Connell'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Vern Tessio', (SELECT id FROM people WHERE people.name = 'Jerry O\'Connell'), (SELECT id FROM movies WHERE movies.title = 'Stand By Me') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Bob Sugar', (SELECT id FROM people WHERE people.name = 'Jay Mohr'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Laurel Boyd', (SELECT id FROM people WHERE people.name = 'Bonnie Hunt'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jan Edgecomb', (SELECT id FROM people WHERE people.name = 'Bonnie Hunt'), (SELECT id FROM movies WHERE movies.title = 'The Green Mile') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Marcee Tidwell', (SELECT id FROM people WHERE people.name = 'Regina King'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Ray Boyd', (SELECT id FROM people WHERE people.name = 'Jonathan Lipnicki'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Chris Chambers', (SELECT id FROM people WHERE people.name = 'River Phoenix'), (SELECT id FROM movies WHERE movies.title = 'Stand By Me') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Teddy Duchamp', (SELECT id FROM people WHERE people.name = 'Corey Feldman'), (SELECT id FROM movies WHERE movies.title = 'Stand By Me') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Gordie Lachance', (SELECT id FROM people WHERE people.name = 'Wil Wheaton'), (SELECT id FROM movies WHERE movies.title = 'Stand By Me') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Denny Lachance', (SELECT id FROM people WHERE people.name = 'John Cusack'), (SELECT id FROM movies WHERE movies.title = 'Stand By Me') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Mr. Lachance', (SELECT id FROM people WHERE people.name = 'Marshall Bell'), (SELECT id FROM movies WHERE movies.title = 'Stand By Me') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Admiral', (SELECT id FROM people WHERE people.name = 'Marshall Bell'), (SELECT id FROM movies WHERE movies.title = 'RescueDawn') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Carol Connelly', (SELECT id FROM people WHERE people.name = 'Helen Hunt'), (SELECT id FROM movies WHERE movies.title = 'As Good as It Gets') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dr. Jo Harding', (SELECT id FROM people WHERE people.name = 'Helen Hunt'), (SELECT id FROM movies WHERE movies.title = 'Twister') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Kelly Frears', (SELECT id FROM people WHERE people.name = 'Helen Hunt'), (SELECT id FROM movies WHERE movies.title = 'Cast Away') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Simon Bishop', (SELECT id FROM people WHERE people.name = 'Greg Kinnear'), (SELECT id FROM movies WHERE movies.title = 'As Good as It Gets') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Frank Navasky', (SELECT id FROM people WHERE people.name = 'Greg Kinnear'), (SELECT id FROM movies WHERE movies.title = 'You\'ve Got Mail') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Simon Bishop', (SELECT id FROM people WHERE people.name = 'Annabella Sciorra'), (SELECT id FROM movies WHERE movies.title = 'What Dreams May Come') );
INSERT INTO roles (role, actor, movie) VALUES ( 'The Tracker', (SELECT id FROM people WHERE people.name = 'Max von Sydow'), (SELECT id FROM movies WHERE movies.title = 'What Dreams May Come') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Nels Gudmundsson', (SELECT id FROM people WHERE people.name = 'Max von Sydow'), (SELECT id FROM movies WHERE movies.title = 'Snow Falling on Cedars') );
INSERT INTO roles (role, actor, movie) VALUES ( 'The Face', (SELECT id FROM people WHERE people.name = 'Werner Herzog'), (SELECT id FROM movies WHERE movies.title = 'What Dreams May Come') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Chris Nielsen', (SELECT id FROM people WHERE people.name = 'Robin Williams'), (SELECT id FROM movies WHERE movies.title = 'What Dreams May Come') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Armand Goldman', (SELECT id FROM people WHERE people.name = 'Robin Williams'), (SELECT id FROM movies WHERE movies.title = 'The Birdcage') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Andrew Marin', (SELECT id FROM people WHERE people.name = 'Robin Williams'), (SELECT id FROM movies WHERE movies.title = 'Bicentennial Man') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Ishmael Chambers', (SELECT id FROM people WHERE people.name = 'Ethan Hawke'), (SELECT id FROM movies WHERE movies.title = 'Snow Falling on Cedars') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Kazuo Miyamoto', (SELECT id FROM people WHERE people.name = 'Rick Yune'), (SELECT id FROM movies WHERE movies.title = 'Snow Falling on Cedars') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Takeshi', (SELECT id FROM people WHERE people.name = 'Rick Yune'), (SELECT id FROM movies WHERE movies.title = 'Ninja Assassin') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Judge Fielding', (SELECT id FROM people WHERE people.name = 'James Cromwell'), (SELECT id FROM movies WHERE movies.title = 'Snow Falling on Cedars') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Warden Hal Moores', (SELECT id FROM people WHERE people.name = 'James Cromwell'), (SELECT id FROM movies WHERE movies.title = 'The Green Mile') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Patricia Eden', (SELECT id FROM people WHERE people.name = 'Parker Posey'), (SELECT id FROM movies WHERE movies.title = 'You\'ve Got Mail') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Kevin Jackson', (SELECT id FROM people WHERE people.name = 'Dave Chappelle'), (SELECT id FROM movies WHERE movies.title = 'You\'ve Got Mail') );
INSERT INTO roles (role, actor, movie) VALUES ( 'George Pappas', (SELECT id FROM people WHERE people.name = 'Steve Zahn'), (SELECT id FROM movies WHERE movies.title = 'You\'ve Got Mail') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Duane', (SELECT id FROM people WHERE people.name = 'Steve Zahn'), (SELECT id FROM movies WHERE movies.title = 'RescueDawn') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Joe Fox', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'You\'ve Got Mail') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Sam Baldwin', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'Sleepless in Seattle') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Joe Banks', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'Joe Versus the Volcano') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Mr. White', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'That Thing You Do') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Zachry', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dr. Henry Goose', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Isaac Sachs', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dermot Hoggins', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dr. Robert Langdon', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'The Da Vinci Code') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Paul Edgecomb', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'The Green Mile') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jim Lovell', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'Apollo 13') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Chuck Noland', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'Cast Away') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Rep. Charlie Wilson', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'Charlie Wilson\'s War') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Hero Boy', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'The Polar Express') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Father', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'The Polar Express') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Conductor', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'The Polar Express') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Hobo', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'The Polar Express') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Scrooge', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'The Polar Express') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Santa Claus', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'The Polar Express') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jimmy Dugan', (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'A League of Their Own') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Suzy', (SELECT id FROM people WHERE people.name = 'Rita Wilson'), (SELECT id FROM movies WHERE movies.title = 'Sleepless in Seattle') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Walter', (SELECT id FROM people WHERE people.name = 'Bill Pullman'), (SELECT id FROM movies WHERE movies.title = 'Sleepless in Seattle') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Greg', (SELECT id FROM people WHERE people.name = 'Victor Garber'), (SELECT id FROM movies WHERE movies.title = 'Sleepless in Seattle') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Becky', (SELECT id FROM people WHERE people.name = 'Rosie O\'Donnell'), (SELECT id FROM movies WHERE movies.title = 'Sleepless in Seattle') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Doris Murphy', (SELECT id FROM people WHERE people.name = 'Rosie O\'Donnell'), (SELECT id FROM movies WHERE movies.title = 'A League of Their Own') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Baw', (SELECT id FROM people WHERE people.name = 'Nathan Lane'), (SELECT id FROM movies WHERE movies.title = 'Joe Versus the Volcano') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Albert Goldman', (SELECT id FROM people WHERE people.name = 'Nathan Lane'), (SELECT id FROM movies WHERE movies.title = 'The Birdcage') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Harry Burns', (SELECT id FROM people WHERE people.name = 'Billy Crystal'), (SELECT id FROM movies WHERE movies.title = 'When Harry Met Sally') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Marie', (SELECT id FROM people WHERE people.name = 'Carrie Fisher'), (SELECT id FROM movies WHERE movies.title = 'When Harry Met Sally') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jess', (SELECT id FROM people WHERE people.name = 'Bruno Kirby'), (SELECT id FROM movies WHERE movies.title = 'When Harry Met Sally') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Faye Dolan', (SELECT id FROM people WHERE people.name = 'Liv Tyler'), (SELECT id FROM movies WHERE movies.title = 'That Thing You Do') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Annabelle Farrell', (SELECT id FROM people WHERE people.name = 'Brooke Langton'), (SELECT id FROM movies WHERE movies.title = 'The Replacements') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jimmy McGinty', (SELECT id FROM people WHERE people.name = 'Gene Hackman'), (SELECT id FROM movies WHERE movies.title = 'The Replacements') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Sen. Kevin Keeley', (SELECT id FROM people WHERE people.name = 'Gene Hackman'), (SELECT id FROM movies WHERE movies.title = 'The Birdcage') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Little Bill Daggett', (SELECT id FROM people WHERE people.name = 'Gene Hackman'), (SELECT id FROM movies WHERE movies.title = 'Unforgiven') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Clifford Franklin', (SELECT id FROM people WHERE people.name = 'Orlando Jones'), (SELECT id FROM movies WHERE movies.title = 'The Replacements') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dieter Dengler', (SELECT id FROM people WHERE people.name = 'Christian Bale'), (SELECT id FROM movies WHERE movies.title = 'RescueDawn') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Squad Leader', (SELECT id FROM people WHERE people.name = 'Zach Grenier'), (SELECT id FROM movies WHERE movies.title = 'RescueDawn') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Eddie', (SELECT id FROM people WHERE people.name = 'Zach Grenier'), (SELECT id FROM movies WHERE movies.title = 'Twister') );
INSERT INTO roles (role, actor, movie) VALUES ( 'English Bob', (SELECT id FROM people WHERE people.name = 'Richard Harris'), (SELECT id FROM movies WHERE movies.title = 'Unforgiven') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Bill Munny', (SELECT id FROM people WHERE people.name = 'Clint Eastwood'), (SELECT id FROM movies WHERE movies.title = 'Unforgiven') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Takahashi', (SELECT id FROM people WHERE people.name = 'Takeshi Kitano'), (SELECT id FROM movies WHERE movies.title = 'Johnny Mnemonic') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jane', (SELECT id FROM people WHERE people.name = 'Dina Meyer'), (SELECT id FROM movies WHERE movies.title = 'Johnny Mnemonic') );
INSERT INTO roles (role, actor, movie) VALUES ( 'J-Bone', (SELECT id FROM people WHERE people.name = 'Ice-T'), (SELECT id FROM movies WHERE movies.title = 'Johnny Mnemonic') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Luisa Rey', (SELECT id FROM people WHERE people.name = 'Halle Berry'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Jocasta Ayrs', (SELECT id FROM people WHERE people.name = 'Halle Berry'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Ovid', (SELECT id FROM people WHERE people.name = 'Halle Berry'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Meronym', (SELECT id FROM people WHERE people.name = 'Halle Berry'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Vyvyan Ayrs', (SELECT id FROM people WHERE people.name = 'Jim Broadbent'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Captain Molyneux', (SELECT id FROM people WHERE people.name = 'Jim Broadbent'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Timothy Cavendish', (SELECT id FROM people WHERE people.name = 'Jim Broadbent'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Sir Leight Teabing', (SELECT id FROM people WHERE people.name = 'Ian McKellen'), (SELECT id FROM movies WHERE movies.title = 'The Da Vinci Code') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Sophie Neveu', (SELECT id FROM people WHERE people.name = 'Audrey Tautou'), (SELECT id FROM movies WHERE movies.title = 'The Da Vinci Code') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Silas', (SELECT id FROM people WHERE people.name = 'Paul Bettany'), (SELECT id FROM movies WHERE movies.title = 'The Da Vinci Code') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Evey Hammond', (SELECT id FROM people WHERE people.name = 'Natalie Portman'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Eric Finch', (SELECT id FROM people WHERE people.name = 'Stephen Rea'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO roles (role, actor, movie) VALUES ( 'High Chancellor Adam Sutler', (SELECT id FROM people WHERE people.name = 'John Hurt'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dascomb', (SELECT id FROM people WHERE people.name = 'Ben Miles'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Cass Jones', (SELECT id FROM people WHERE people.name = 'Ben Miles'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Ryan Maslow', (SELECT id FROM people WHERE people.name = 'Ben Miles'), (SELECT id FROM movies WHERE movies.title = 'Ninja Assassin') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Speed Racer', (SELECT id FROM people WHERE people.name = 'Emile Hirsch'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Pops', (SELECT id FROM people WHERE people.name = 'John Goodman'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Mom', (SELECT id FROM people WHERE people.name = 'Susan Sarandon'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Racer X', (SELECT id FROM people WHERE people.name = 'Matthew Fox'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Trixie', (SELECT id FROM people WHERE people.name = 'Christina Ricci'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Taejo Togokahn', (SELECT id FROM people WHERE people.name = 'Rain'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Raizo', (SELECT id FROM people WHERE people.name = 'Rain'), (SELECT id FROM movies WHERE movies.title = 'Ninja Assassin') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Mika Coretti', (SELECT id FROM people WHERE people.name = 'Naomie Harris'), (SELECT id FROM movies WHERE movies.title = 'Ninja Assassin') );
INSERT INTO roles (role, actor, movie) VALUES ( 'John Coffey', (SELECT id FROM people WHERE people.name = 'Michael Clarke Duncan'), (SELECT id FROM movies WHERE movies.title = 'The Green Mile') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Brutus \'Brutal\' Howell', (SELECT id FROM people WHERE people.name = 'David Morse'), (SELECT id FROM movies WHERE movies.title = 'The Green Mile') );
INSERT INTO roles (role, actor, movie) VALUES ( '\'Wild Bill\' Wharton', (SELECT id FROM people WHERE people.name = 'Sam Rockwell'), (SELECT id FROM movies WHERE movies.title = 'The Green Mile') );
INSERT INTO roles (role, actor, movie) VALUES ( 'James Reston, Jr.', (SELECT id FROM people WHERE people.name = 'Sam Rockwell'), (SELECT id FROM movies WHERE movies.title = 'Frost/Nixon') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Burt Hammersmith', (SELECT id FROM people WHERE people.name = 'Gary Sinise'), (SELECT id FROM movies WHERE movies.title = 'The Green Mile') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Ken Mattingly', (SELECT id FROM people WHERE people.name = 'Gary Sinise'), (SELECT id FROM movies WHERE movies.title = 'Apollo 13') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Melinda Moores', (SELECT id FROM people WHERE people.name = 'Patricia Clarkson'), (SELECT id FROM movies WHERE movies.title = 'The Green Mile') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Richard Nixon', (SELECT id FROM people WHERE people.name = 'Frank Langella'), (SELECT id FROM movies WHERE movies.title = 'Frost/Nixon') );
INSERT INTO roles (role, actor, movie) VALUES ( 'David Frost', (SELECT id FROM people WHERE people.name = 'Michael Sheen'), (SELECT id FROM movies WHERE movies.title = 'Frost/Nixon') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Bob Zelnick', (SELECT id FROM people WHERE people.name = 'Oliver Platt'), (SELECT id FROM movies WHERE movies.title = 'Frost/Nixon') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Rupert Burns', (SELECT id FROM people WHERE people.name = 'Oliver Platt'), (SELECT id FROM movies WHERE movies.title = 'Bicentennial Man') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Robert \'Bobby\' Ciaro', (SELECT id FROM people WHERE people.name = 'Danny DeVito'), (SELECT id FROM movies WHERE movies.title = 'Hoffa') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Martini', (SELECT id FROM people WHERE people.name = 'Danny DeVito'), (SELECT id FROM movies WHERE movies.title = 'One Flew Over the Cuckoo\'s Nest') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Peter \'Pete\' Connelly', (SELECT id FROM people WHERE people.name = 'John C. Reilly'), (SELECT id FROM movies WHERE movies.title = 'Hoffa') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Gene Kranz', (SELECT id FROM people WHERE people.name = 'Ed Harris'), (SELECT id FROM movies WHERE movies.title = 'Apollo 13') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Fred Haise', (SELECT id FROM people WHERE people.name = 'Bill Paxton'), (SELECT id FROM movies WHERE movies.title = 'Apollo 13') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Bill Harding', (SELECT id FROM people WHERE people.name = 'Bill Paxton'), (SELECT id FROM movies WHERE movies.title = 'Twister') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Bob Hinson', (SELECT id FROM people WHERE people.name = 'Bill Paxton'), (SELECT id FROM movies WHERE movies.title = 'A League of Their Own') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dustin \'Dusty\' Davis', (SELECT id FROM people WHERE people.name = 'Philip Seymour Hoffman'), (SELECT id FROM movies WHERE movies.title = 'Twister') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Gust Avrakotos', (SELECT id FROM people WHERE people.name = 'Philip Seymour Hoffman'), (SELECT id FROM movies WHERE movies.title = 'Charlie Wilson\'s War') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Erica Barry', (SELECT id FROM people WHERE people.name = 'Diane Keaton'), (SELECT id FROM movies WHERE movies.title = 'Something\'s Gotta Give') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Joanne Herring', (SELECT id FROM people WHERE people.name = 'Julia Roberts'), (SELECT id FROM movies WHERE movies.title = 'Charlie Wilson\'s War') );
INSERT INTO roles (role, actor, movie) VALUES ( '\'All the Way\' Mae Mordabito', (SELECT id FROM people WHERE people.name = 'Madonna'), (SELECT id FROM movies WHERE movies.title = 'A League of Their Own') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Dottie Hinson', (SELECT id FROM people WHERE people.name = 'Geena Davis'), (SELECT id FROM movies WHERE movies.title = 'A League of Their Own') );
INSERT INTO roles (role, actor, movie) VALUES ( 'Kit Keller', (SELECT id FROM people WHERE people.name = 'Lori Petty'), (SELECT id FROM movies WHERE movies.title = 'A League of Their Own') );
INSERT INTO reviews (rating, summary, author, movie) VALUES ( 62, 'Pretty funny at times', (SELECT id FROM people WHERE people.name = 'Angela Scope'), (SELECT id FROM movies WHERE movies.title = 'The Replacements') );
INSERT INTO reviews (rating, summary, author, movie) VALUES ( 95, 'An amazing journey', (SELECT id FROM people WHERE people.name = 'Jessica Thompson'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO reviews (rating, summary, author, movie) VALUES ( 65, 'Silly, but fun', (SELECT id FROM people WHERE people.name = 'Jessica Thompson'), (SELECT id FROM movies WHERE movies.title = 'The Replacements') );
INSERT INTO reviews (rating, summary, author, movie) VALUES ( 85, 'Dark, but compelling', (SELECT id FROM people WHERE people.name = 'Jessica Thompson'), (SELECT id FROM movies WHERE movies.title = 'Unforgiven') );
INSERT INTO reviews (rating, summary, author, movie) VALUES ( 45, 'Slapstick redeemed only by the Robin Williams and Gene Hackman\'s stellar performances', (SELECT id FROM people WHERE people.name = 'Jessica Thompson'), (SELECT id FROM movies WHERE movies.title = 'The Birdcage') );
INSERT INTO reviews (rating, summary, author, movie) VALUES ( 68, 'A solid romp', (SELECT id FROM people WHERE people.name = 'Jessica Thompson'), (SELECT id FROM movies WHERE movies.title = 'The Da Vinci Code') );
INSERT INTO reviews (rating, summary, author, movie) VALUES ( 92, 'You had me at Jerry', (SELECT id FROM people WHERE people.name = 'Jessica Thompson'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO reviews (rating, summary, author, movie) VALUES ( 100, 'The coolest football movie ever', (SELECT id FROM people WHERE people.name = 'James Thompson'), (SELECT id FROM movies WHERE movies.title = 'The Replacements') );
INSERT INTO reviews (rating, summary, author, movie) VALUES ( 65, 'Fun, but a little far fetched', (SELECT id FROM people WHERE people.name = 'James Thompson'), (SELECT id FROM movies WHERE movies.title = 'The Da Vinci Code') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Andy Wachowski'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Andy Wachowski'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Lana Wachowski'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Lana Wachowski'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Aaron Sorkin'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Jim Cash'), (SELECT id FROM movies WHERE movies.title = 'Top Gun') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Cameron Crowe'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Nora Ephron'), (SELECT id FROM movies WHERE movies.title = 'When Harry Met Sally') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'David Mitchell'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO wrote (author, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Nancy Meyers'), (SELECT id FROM movies WHERE movies.title = 'Something\'s Gotta Give') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Andy Wachowski'), (SELECT id FROM movies WHERE movies.title = 'The Matrix') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Andy Wachowski'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Reloaded') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Andy Wachowski'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Revolutions') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Andy Wachowski'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Andy Wachowski'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Lana Wachowski'), (SELECT id FROM movies WHERE movies.title = 'The Matrix') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Lana Wachowski'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Reloaded') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Lana Wachowski'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Revolutions') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Lana Wachowski'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Lana Wachowski'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Taylor Hackford'), (SELECT id FROM movies WHERE movies.title = 'The Devil\'s Advocate') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'James Marshall'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'James Marshall'), (SELECT id FROM movies WHERE movies.title = 'Ninja Assassin') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Rob Reiner'), (SELECT id FROM movies WHERE movies.title = 'A Few Good Men') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Rob Reiner'), (SELECT id FROM movies WHERE movies.title = 'Stand By Me') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Rob Reiner'), (SELECT id FROM movies WHERE movies.title = 'When Harry Met Sally') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Tony Scott'), (SELECT id FROM movies WHERE movies.title = 'Top Gun') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Cameron Crowe'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'James L. Brooks'), (SELECT id FROM movies WHERE movies.title = 'As Good as It Gets') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Werner Herzog'), (SELECT id FROM movies WHERE movies.title = 'RescueDawn') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Vincent Ward'), (SELECT id FROM movies WHERE movies.title = 'What Dreams May Come') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Scott Hicks'), (SELECT id FROM movies WHERE movies.title = 'Snow Falling on Cedars') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Tom Hanks'), (SELECT id FROM movies WHERE movies.title = 'That Thing You Do') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Nora Ephron'), (SELECT id FROM movies WHERE movies.title = 'You\'ve Got Mail') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Nora Ephron'), (SELECT id FROM movies WHERE movies.title = 'Sleepless in Seattle') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'John Patrick Stanley'), (SELECT id FROM movies WHERE movies.title = 'Joe Versus the Volcano') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Howard Deutch'), (SELECT id FROM movies WHERE movies.title = 'The Replacements') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Mike Nichols'), (SELECT id FROM movies WHERE movies.title = 'The Birdcage') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Mike Nichols'), (SELECT id FROM movies WHERE movies.title = 'Charlie Wilson\'s War') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Clint Eastwood'), (SELECT id FROM movies WHERE movies.title = 'Unforgiven') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Robert Longo'), (SELECT id FROM movies WHERE movies.title = 'Johnny Mnemonic') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Tom Tykwer'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Ron Howard'), (SELECT id FROM movies WHERE movies.title = 'The Da Vinci Code') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Ron Howard'), (SELECT id FROM movies WHERE movies.title = 'Frost/Nixon') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Ron Howard'), (SELECT id FROM movies WHERE movies.title = 'Apollo 13') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Frank Darabont'), (SELECT id FROM movies WHERE movies.title = 'The Green Mile') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Danny DeVito'), (SELECT id FROM movies WHERE movies.title = 'Hoffa') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Jan de Bont'), (SELECT id FROM movies WHERE movies.title = 'Twister') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Robert Zemeckis'), (SELECT id FROM movies WHERE movies.title = 'Cast Away') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Robert Zemeckis'), (SELECT id FROM movies WHERE movies.title = 'The Polar Express') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Milos Forman'), (SELECT id FROM movies WHERE movies.title = 'One Flew Over the Cuckoo\'s Nest') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Nancy Meyers'), (SELECT id FROM movies WHERE movies.title = 'Something\'s Gotta Give') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Chris Columbus'), (SELECT id FROM movies WHERE movies.title = 'Bicentennial Man') );
INSERT INTO directed (director, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Penny Marshall'), (SELECT id FROM movies WHERE movies.title = 'A League of Their Own') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Andy Wachowski'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Andy Wachowski'), (SELECT id FROM movies WHERE movies.title = 'Ninja Assassin') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Lana Wachowski'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Lana Wachowski'), (SELECT id FROM movies WHERE movies.title = 'Ninja Assassin') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Joel Silver'), (SELECT id FROM movies WHERE movies.title = 'The Matrix') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Joel Silver'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Reloaded') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Joel Silver'), (SELECT id FROM movies WHERE movies.title = 'The Matrix Revolutions') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Joel Silver'), (SELECT id FROM movies WHERE movies.title = 'V for Vendetta') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Joel Silver'), (SELECT id FROM movies WHERE movies.title = 'Speed Racer') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Joel Silver'), (SELECT id FROM movies WHERE movies.title = 'Ninja Assassin') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Rob Reiner'), (SELECT id FROM movies WHERE movies.title = 'When Harry Met Sally') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Cameron Crowe'), (SELECT id FROM movies WHERE movies.title = 'Jerry Maguire') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Nora Ephron'), (SELECT id FROM movies WHERE movies.title = 'When Harry Met Sally') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Stefan Arndt'), (SELECT id FROM movies WHERE movies.title = 'Cloud Atlas') );
INSERT INTO produced (producer, movie) VALUES ( (SELECT id FROM people WHERE people.name = 'Nancy Meyers'), (SELECT id FROM movies WHERE movies.title = 'Something\'s Gotta Give') );
